// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvzo11Kh-T-E1GKHl1aB7gFFEKmimLgA8',
    appId: '1:1091583858659:web:3520b1b6ebcba003b032d6',
    messagingSenderId: '1091583858659',
    projectId: 'easyvastra',
    authDomain: 'easyvastra.firebaseapp.com',
    storageBucket: 'easyvastra.appspot.com',
    measurementId: 'G-2NDMP9NTGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjCpoPX4AY2yTMXWGx_iUVRJt-19Hxnb8',
    appId: '1:1091583858659:android:32776461019616f3b032d6',
    messagingSenderId: '1091583858659',
    projectId: 'easyvastra',
    storageBucket: 'easyvastra.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4ioW8gzKGML-OcwlqWtYUherkF0x8J9A',
    appId: '1:1091583858659:ios:5e0c70bec617a36db032d6',
    messagingSenderId: '1091583858659',
    projectId: 'easyvastra',
    storageBucket: 'easyvastra.appspot.com',
    iosBundleId: 'com.edioticvishal.easyVastra',
  );
}
